### ISSUE TITLE
做的不错，加油！

### ISSUE THREAD

**Issue by maoruibin** [CaMnter/EasyGank#1]
只看了界面，看得出花了不少功夫，效果挺赞.

不过项目中有一些错别字，干货(活)集中营 ，还有，侧边栏中没有 App 这个item.

**Comment by CaMnter** [comment]
啊，是这样的。api网写
数据类型： 福利 | Android | iOS | 休息视频 | 拓展资源 | 前端 | all   
没看到App 哈哈，后续加吧，谢谢提醒，其实也简单我的Adapter用的一个，加一个数据类型和菜单就可以，谢谢。 :)

**Comment by CaMnter** [comment]
@maoruibin  错别字改了，真厉害，cmd+shift+f搜了一下竟然在关于页面，那个页面我写完都没看过一次了，不喜欢看自己 T T， app模块也加了，才发现你是栏主 :+1:

**Comment by maoruibin** [comment]
不错，改的挺快嘛，good night~

**Comment by CaMnter** [comment]
@maoruibin https://github.com/CaMnter/EasyGank/commit/758e9b785730c3a38dbd5d198a15168eb20e5db3
前期的构思，现在看来用处真大。
