### ISSUE TITLE
android studio 2.3 强制要求 gradle 插件2.3.0，然后报错

### ISSUE THREAD

**Issue by LiJia92** [CaMnter/EasyGank#11]
应该是第三方不兼容导致，log：
> Error:Unable to load class 'org.gradle.logging.StyledTextOutput$Style'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by CaMnter** [comment]
```shell
git checkout -- build.gradle
git checkout gradle/gradle-wrapper.properties
```

项目用 android studio 2.3 跑也可以。插件回退一下一样的。
