### ISSUE TITLE
把gradle文件夹放进来吧, 方便下载下来直接编译

### ISSUE THREAD

**Issue by ssthouse** [CaMnter/EasyGank#3]
如题

**Comment by CaMnter** [comment]
@ssthouse ，是gradle的插件下不下来还是gradle？gradle的文件夹有60M。

**Comment by ssthouse** [comment]
![image](https://cloud.githubusercontent.com/assets/10973821/13591295/30bb3860-e522-11e5-93a2-ab77d19a2ab7.png)
是项目根目录的gradle文件夹,应该是很小的50k的样子

**Comment by CaMnter** [comment]
@ssthouse  这个不是gradle... http://www.devdiv.com/Android-gradle_gradle_wrapper_-thread-214388-1-1.html

**Comment by CaMnter** [comment]
@ssthouse 提交了
