### ISSUE TITLE
求realse中给打包好的apk

### ISSUE THREAD

**Issue by HakuLess** [CaMnter/EasyGank#4]
如题~ 想直接用apk体验下

**Comment by CaMnter** [comment]
@HakuLess  realse是我打tag时顺手打的...最新版本一直在 
http://fir.im/easygank
https://github.com/CaMnter/EasyGank/blob/master/app/EasyGank_v1.2_2016-03-18_Github.apk

**Comment by HakuLess** [comment]
收到 thankyou

**Comment by CaMnter** [comment]
@HakuLess  (｡>﹏<｡)
