### ISSUE TITLE
营养跟不上啊

### ISSUE THREAD

**Issue by sevenmine** [CaMnter/EasyGank#6]
本来是准备下下来看下MVP框架的，想不到一进去就是福利。可耻的我在公司偷偷的看完了所有福利，喝了两瓶营养快线才缓过来。强烈谴责楼主这样的给图不给种的行为

**Comment by CaMnter** [comment]
@sevenmine 不对吧，大兄弟，我首页是缩略图，都能石更？ (｡>﹏<｡)
