### ISSUE TITLE
DataManager 讨论

### ISSUE THREAD

**Issue by gzfgeh** [CaMnter/EasyGank#7]
个人仔细读了你的代码，不知道DataManager的作用，我在Presenter中直接用自己的Model就行了，麻烦告诉DataManager的作用，百思不得其解

**Comment by CaMnter** [comment]
@gzfgeh  DataManager本来想在这个做数据加载的，因为网络有可能差，就读本地db的数据。
DataManager是负责加载数据，我只负责问DataManager要数据。但是后来我没加入db的缓存，用的是一个Rx的文件缓存库子。所以目前DataManager看不出效果，然后...就一直酱紫了 (｡>﹏<｡)

**Comment by gzfgeh** [comment]
我现在有个需求就是，从后台拿到两部分数据，我用Rx只能返回一部分数据，zip和flatMap虽说可以处理多条数据，但是返回给Activity的还是一部分数据，我想问问有什么方法让我同时返回给Activity两部分数据，我现在做法是先请求一部分数据，然后在请求另一部分数据，但是这样感觉不太好，这两部分数据其实是同时被我拿到的，请问有啥好方法吗？ 有QQ吗 交流下 我的305475422

**Comment by CaMnter** [comment]
@gzfgeh 微信：SaveYouFromAnything7
